import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'

import MuiContainer from '@mui/material/Container'
import { HeaderContainer } from '@containers/HeaderContainer'
import { MainContainer } from '@containers/MainContainer'

import useMediaQuery from '@mui/material/useMediaQuery'
import theme from '@themes/main.theme'
import { ThemeProvider } from '@mui/material/styles'

const Home: NextPage = () => {
  const matches = useMediaQuery('(min-width:1600px)') // слушатель ширина окна
  const [sliderSerialNum, setSliderSerialNum] = React.useState<number>(0)

  return (
    <div>
      <Head>
        <title>crypto-coin</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='fonts/GothamPro/stylesheet.css'
          rel='stylesheet'
          type='text/css'
        />
      </Head>

      <ThemeProvider theme={theme}>
        <MuiContainer
          disableGutters={matches} // убрать отступы(padding по бокам), если ширина больше 1600px
          sx={{ maxWidth: { xs: '100%', xl: '1278px' } }}
        >
          <HeaderContainer
            sliderSerialNum={sliderSerialNum} // для отображения текущего слайда
            setSliderSerialNum={setSliderSerialNum} // для смены слайда
          />
          <MainContainer />
        </MuiContainer>
      </ThemeProvider>
    </div>
  )
}

export default Home
